### ISSUE TITLE
Using 'chart_attr' with a dot adds extra ':' in javascript

### ISSUE THREAD

**Issue by AlexejStukov** [areski/django-nvd3#69]
Using 
```python
extra = {
    'x_is_date': False,
    'x_axis_format': '',
    'jquery_on_ready': False,
    'chart_attr': {'xAxis': '.rotateLabels(45)'}
}
chart = load_chart("discreteBarChart", {"x": xdata, "y": ydata}, "chartcontainer", extra)
```
leads to an extra ``:`` in the Javascript output:
```javascript
// ...
        var datum = data_chartcontainer;

        chart.color(d3.scale.category20().range());


                    chart.yAxis
                .tickFormat(d3.format(',.0f'));

    
    :    // <-- extra ":"
                chart.xAxis.rotateLabels(45);
// ...
```
If I use something without the dot, e.g. ``'chart_attr':{"margin":"{top: 30, right: 100, bottom: 200, left: 60}"}'``  it works perfectly fine. Also if I replace that ``:`` the Javascript executes without an error.

**Comment by AlexejStukov** [comment]
Issue was resolved in upstream

**Comment by nickongit** [comment]
@AlexejStukov can you elaborate on what I need to fix this. I've updated django-nvd3 to django-nvd3==0.9.7 but I still get the same behaviour. 

Thanks, and thank-you for writing this great app.

**Comment by nickongit** [comment]
It's OK, I think I have worked it out.

        'extra': {
                    'chart_attr': {'xAxis.rotateLabels': '-25'},
                 }

**Comment by AlexejStukov** [comment]
@nickongit: It was fixed in python-nvd3, but i think it's not released yet. Should be included in the next version.
